name: Deploy Report to Vercel

on:
  push:
    branches:
      - v.4.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate HTML Report
        run: python devrev_merge.py --csv contacts.csv --preview

      # Add debug steps to verify file generation and content
      - name: Debug - List directory structure
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -R

      - name: Debug - Check reports directory
        run: |
          if [ -d "reports" ]; then
            echo "Reports directory exists"
            ls -la reports/
          else
            echo "Reports directory not found"
          fi

      # Modified copy step with error checking
      - name: Set latest report as index.html
        run: |
          if [ -d "reports" ]; then
            latest=$(ls -t reports/merge_report_*.html 2>/dev/null | head -n 1)
            if [ -n "$latest" ]; then
              echo "Found latest report: $latest"
              cp "$latest" reports/index.html
              echo "Content of index.html:"
              head -n 5 reports/index.html
            else
              echo "No report files found!"
              exit 1
            fi
          else
            echo "Reports directory not found!"
            exit 1
          fi

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: './reports'  # Changed to deploy from reports directory
          prod: true